[package]
org = "shazni"
name = "Test"
version = "0.1.0"
distribution = "2201.3.2"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"
